### ISSUE TITLE
About tex file

### ISSUE THREAD

**Issue by rlacjfjin** [lullcant/Convex-Optimization#1]
Hi,

is it possible to upload tex files? 

Thanks.

Zhe.

**Comment by lullcant** [comment]
Hi，
Sorry, I'm busy with research and learning of reading paper about deep learning. I will delay my updating of my convex optimization learning note repo. But once I have relatively large update on my note. tex files will be uploaded.


Best wishes,
Linda



1052366032
***@***.***







                       
Original
                       
                     

From:"rlacjfjin"< ***@***.*** &gt;;

Date:2023/1/26 0:09

To:"lullcant/Convex-Optimization"< ***@***.*** &gt;;

CC:"Subscribed"< ***@***.*** &gt;;

Subject:[lullcant/Convex-Optimization] About tex file (Issue #1)




 
Hi,
 
is it possible to upload tex files?
 
Thanks.
 
Zhe.

**Comment by rlacjfjin** [comment]
OK, Thanks.
